//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18051
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBACore.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMBACore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap admin_64 {
            get {
                object obj = ResourceManager.GetObject("admin_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAddClass {
            get {
                object obj = ResourceManager.GetObject("btnAddClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAddCourse {
            get {
                object obj = ResourceManager.GetObject("btnAddCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnaddstudent_image {
            get {
                object obj = ResourceManager.GetObject("btnaddstudent_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnAddTeacher {
            get {
                object obj = ResourceManager.GetObject("btnAddTeacher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnDeleteClass {
            get {
                object obj = ResourceManager.GetObject("btnDeleteClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnDeleteCourse {
            get {
                object obj = ResourceManager.GetObject("btnDeleteCourse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btndeletestudent_image {
            get {
                object obj = ResourceManager.GetObject("btndeletestudent_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnDeleteTeacher {
            get {
                object obj = ResourceManager.GetObject("btnDeleteTeacher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap calc_save_64 {
            get {
                object obj = ResourceManager.GetObject("calc_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ClassIcon {
            get {
                object obj = ResourceManager.GetObject("ClassIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;課程基本資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學年度+學期+開課&quot;&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;開課&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///        &lt;Detector Name=&quot;開課系統編號&quot;&gt;
        ///            &lt;Field Name=&quot;開課系統編號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--課程系統編號	開課,學年度,學期,開課班次,類別,課程識別碼,課號,學分數,必選修,流水號,人數上限--&gt;        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Course_Import {
            get {
                return ResourceManager.GetString("Course_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap course_plan {
            get {
                object obj = ResourceManager.GetObject("course_plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CourseIcon {
            get {
                object obj = ResourceManager.GetObject("CourseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Crystal_Clear_action_lock_silver {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_lock_silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] EMBA_歷年成績表_樣版 {
            get {
                object obj = ResourceManager.GetObject("EMBA_歷年成績表_樣版", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] EMBA_研究生成績審核表_樣版 {
            get {
                object obj = ResourceManager.GetObject("EMBA_研究生成績審核表_樣版", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportScoreImage {
            get {
                object obj = ResourceManager.GetObject("ExportScoreImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("folder_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap forbidden {
            get {
                object obj = ResourceManager.GetObject("forbidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap foreign_key_lock_64 {
            get {
                object obj = ResourceManager.GetObject("foreign_key_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///&lt;xsl:variable name=&quot;error&quot;&gt;Error&lt;/xsl:variable&gt;
        ///&lt;xsl:variable name=&quot;warning&quot;&gt;Warning&lt;/xsl:variable&gt;
        ///&lt;xsl:variable name=&quot;true&quot;&gt;TRUE&lt;/xsl:variable&gt;
        ///&lt;xsl:variable name=&quot;false&quot;&gt;FALSE&lt;/xsl:variable&gt;
        ///&lt;xsl:variable name=&quot;smallcase&quot; select=&quot;&apos;abcdefghijklmnopqrstuvwxyz&apos;&quot; /&gt;
        ///&lt;xsl:variable name=&quot;uppercase&quot; select=&quot;&apos;ABCDEFGHIJKLMNOPQRSTUVWXYZ&apos;&quot; /&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///	&lt;s [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;GradeScoreMappingTable&gt;
        ///    &lt;Grade GP=&quot;4.3&quot; Score=&quot;95&quot;&gt;A+&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;4.0&quot; Score=&quot;87&quot;&gt;A&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;3.7&quot; Score=&quot;82&quot;&gt;A-&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;3.3&quot; Score=&quot;78&quot;&gt;B+&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;3.0&quot; Score=&quot;75&quot;&gt;B&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;2.7&quot; Score=&quot;70&quot;&gt;B-&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;2.3&quot; Score=&quot;68&quot;&gt;C+&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;2.0&quot; Score=&quot;65&quot;&gt;C&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;1.7&quot; Score=&quot;60&quot;&gt;C-&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;0&quot; Score=&quot;50&quot;&gt;F&lt;/Grade&gt;
        ///    &lt;Grade GP=&quot;0&quot; Score=&quot;0&quot;&gt;X&lt;/Grade&gt;
        ///&lt;/GradeScoreMappingTabl [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string GradeScoreMappingTable {
            get {
                return ResourceManager.GetString("GradeScoreMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap group_64 {
            get {
                object obj = ResourceManager.GetObject("group_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icon64_school_info {
            get {
                object obj = ResourceManager.GetObject("icon64_school_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ImportScoreImage {
            get {
                object obj = ResourceManager.GetObject("ImportScoreImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap network_lock_64 {
            get {
                object obj = ResourceManager.GetObject("network_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh_window_64 {
            get {
                object obj = ResourceManager.GetObject("refresh_window_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;修課學生&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學年度+學期+開課+學號&quot;&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;開課&quot; /&gt;   &lt;!-- 即「課程名稱：course_name」 --&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--課號、課程識別碼、學年度、學期、學號、報告小組--&gt;
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;開課&quot; Description= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SCAttendExt_Import {
            get {
                return ResourceManager.GetString("SCAttendExt_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap searchHistory {
            get {
                object obj = ResourceManager.GetObject("searchHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;學生基本資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學號&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--&amp;lt;BR /&amp;gt;2、請選擇「學號」為「新增資料」的識別欄位。--&gt;
        ///        &lt;Field Required=&quot;False&quot; Name=&quot;教學分班&quot; Description=&quot;&quot; EmptyAlsoValidate=&quot;False&quot; /&gt;
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot; Description=&quot;同步自「校務系統」，只做為識別欄位，不被匯入。&quot; /&gt;
        ///        &lt; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Student_Brief_Import {
            get {
                return ResourceManager.GetString("Student_Brief_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;學生經歷資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學號+公司名稱&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///            &lt;Field Name=&quot;公司名稱&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--「學號」為識別欄位。--&gt;
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot; Description=&quot;識別學生項目。&quot; &gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Student_Experience_Import {
            get {
                return ResourceManager.GetString("Student_Experience_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;論文及指導教授&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學號&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--論文中文名稱	論文英文名稱	是否公開紙本論文	延後公開期限	書籍狀況	指導教授--&gt;
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot; Description=&quot;識別欄位&quot; /&gt;
        ///        &lt;Field Required=&quot;False&quot; Name=&quot;論文題目&quot; Description=&quot;&quot; EmptyAlsoValidate=&quot;False&quot; /&gt;
        ///        &lt;Field Require [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Student_Paper_Import {
            get {
                return ResourceManager.GetString("Student_Paper_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;繳費記錄&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學號&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot; Description=&quot;學號&quot; /&gt;
        ///        &lt;Field Required=&quot;False&quot; Name=&quot;學年期:900&quot; Description=&quot;90學年度夏季學期繳費標記&quot; &gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學年期:900」不可空白，允許值：0(未繳)、1(已繳)。&quot; ErrorTy [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Student_Payment_History_Import {
            get {
                return ResourceManager.GetString("Student_Payment_History_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap StudentIcon {
            get {
                object obj = ResourceManager.GetObject("StudentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;課程總檔&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;課程識別碼&quot;&gt;
        ///            &lt;Field Name=&quot;課程識別碼&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///        &lt;Detector Name=&quot;課號&quot;&gt;
        ///            &lt;Field Name=&quot;課號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///        &lt;Detector Name=&quot;課程系統編號&quot;&gt;
        ///            &lt;Field Name=&quot;課程系統編號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;!--課程系統編號	課程中文名稱	課程英文名稱	課程識別碼	開課系所	系所代碼	學分數 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Subject_Import {
            get {
                return ResourceManager.GetString("Subject_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;學期科目成績&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;學號+學年度+學期+課程識別碼&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;課程識別碼&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///        &lt;Detector Name=&quot;學號+學年度+學期+課號&quot;&gt;
        ///            &lt;Field Name=&quot;學號&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field N [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SubjectSemesterScore_Import {
            get {
                return ResourceManager.GetString("SubjectSemesterScore_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;教師基本資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;姓名+暱稱&quot;&gt;
        ///            &lt;Field Name=&quot;姓名&quot; /&gt;
        ///            &lt;Field Name=&quot;暱稱&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///        &lt;Detector Name=&quot;教師系統編號&quot;&gt;
        ///            &lt;Field Name=&quot;教師系統編號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///        &lt;Field Required=&quot;False&quot; Name=&quot;教師系統編號&quot; Description=&quot;教師系統編號(teacher_id)&quot; EmptyAlsoValidate=&quot;False&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Teacher_Import {
            get {
                return ResourceManager.GetString("Teacher_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap TeacherIcon {
            get {
                object obj = ResourceManager.GetObject("TeacherIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap user_write_64 {
            get {
                object obj = ResourceManager.GetObject("user_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap warning1 {
            get {
                object obj = ResourceManager.GetObject("warning1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap world_upload_64 {
            get {
                object obj = ResourceManager.GetObject("world_upload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 座位表_100A {
            get {
                object obj = ResourceManager.GetObject("座位表_100A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 座位表_100B {
            get {
                object obj = ResourceManager.GetObject("座位表_100B", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 選課名單樣版 {
            get {
                object obj = ResourceManager.GetObject("選課名單樣版", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 重新整理 {
            get {
                object obj = ResourceManager.GetObject("重新整理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢型別 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 點名單樣版 {
            get {
                object obj = ResourceManager.GetObject("點名單樣版", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
